# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Test
      run: go test -v ./...

    - name: Build for all platforms
      run: make build-all

    - name: Artifacts for MacOS platform
      uses: actions/upload-artifact@v3
      with:
        name: mhttp-mac
        path: bin/mac-*

    - name: Artifacts for Linux platform
      uses: actions/upload-artifact@v3
      with:
        name: mhttp-linux
        path: bin/linux-*

    - name: Artifacts for Windows platform
      uses: actions/upload-artifact@v3
      with:
        name: mhttp-windows
        path: bin/win-*


